services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "6033:3306"
    volumes:
      - db_data26:/var/lib/mysql
      - ./workspace:/workspace
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - db
    restart: always
    ports:
      - '88:80'
    environment:
      PMA_HOST: db
volumes:
  db_data26:
